name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        npm install markdownlint-cli

    - name: Run Pylint
      run: |
        if ls **/*.py 1> /dev/null 2>&1; then pylint **/*.py; else echo "No Python files to lint"; fi

    - name: Run Markdownlint
      run: |
        markdownlint **/*.md